research_task:
  description: >
    Identify the video {topic}. Get detailed information about the video from the channel.
  expected_output: >
    A comprehensive 3 paragraphs long report based on the {topic} of video content.
  agent: blog_researcher
  tools: [yt_tool]

writing_task:
  description: >
    Get information from the YT channel on the topic {topic}.
  expected_output: >
    Summarize the info from the YT channel's video on the topic {topic} and create content for the blog.
  agent: blog_writer
  tools: [yt_tool]
  output_file: new-blog-post.md
